### ISSUE TITLE
no tmux session/window is spawned

### ISSUE THREAD

**Issue by vbauerster** [lenormf/kakmerge#4]
I've configured test repo like this:

```
[merge]
	tool = kakmerge
[mergetool "kakmerge"]
	trustExitCode = true
	cmd = env LOCAL=\"${LOCAL}\" BASE=\"${BASE}\" REMOTE=\"${REMOTE}\" MERGED=\"${MERGED}\" kakmerge
```

Invoking `git mergetool` spawns no new tmux session or window. 
I'm on macOS, iterm2 and tmux v3.1c

**Comment by lenormf** [comment]
Thanks for the report, it's indeed broken for me too. I'll look into it!

**Comment by lenormf** [comment]
I released a fix. Note that the documentation was incorrect, the `cmd` bit is unnecessary, you should only need `path`. This is what I have in my configuration:

```
[merge]
    tool = kakmerge

[mergetool "kakmerge"]
    trustExitCode = true
    path = kakmerge
```
