### ISSUE TITLE
Use kakmerge for stand-alone diffs as well?

### ISSUE THREAD

**Issue by dmerejkowsky** [lenormf/kakmerge#9]
Sometimes you need to merge two files outside the context of a git merge - (Using `pacdiff` on an Arch Linux machine to handle `.pacnew` files for instance).

Right now it give the following error message:

```
The required environment variables exported during a merge are missing
```

I'm wondering if this is a use-case you intent to support?

**Comment by lenormf** [comment]
I don't intend to make this tool usable outside the context of a Git merge, or turn it into a patch editor.

You might be able to get something going by implementing a light wrapper for the [patchutils](http://cyberelk.net/tim/software/patchutils/) utilities.

**Comment by dmerejkowsky** [comment]
Fair enough :)
